### ISSUE TITLE
App Release Milestone

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#585]
- [x] Complete all (non v2.0) issues in the `28-8-2023 V2 beta testing` google document
- [x] Add new app store descriptions
- [x] Add app store video
- [x] Create screenshots -> Designer
- [x] App Release
- [x] FAQ Update
